<?php

/**
 * Octopus-IT Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE-COMMUNITY.txt
 * 
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   OCTOPUS
 * @package    Octopus_Deposit
 * @copyright  Copyright (c) 2010-2011 Octopus-IT. (http://www.octopus-it.com)
 * @license    http://www.octopus-it.com/license.txr
 */
$installer = $this;

/* $installer Mage_Core_Model_Resource_Setup */

$installer->startSetup();
$installer->addAttribute(
    'quote_item', 	// the table it's going to either quote_item or order_item 
    'octopus_deposit_remain', // my new attribute 
	array(
        'type'              => 'decimal',
		'grid'           	=> true,
        'backend'           => '',
        'frontend'          => '',
        //'label'             => 'AutoGenerated '.$_attribute_namespace.' - '.$entity_code,
        'input'             => '',
        'class'             => '',
        'source'            => '',
        'global'            => 2,
        'visible'           => true,
        'required'          => false,
        'user_defined'      => false,
        'default'           => '0',
        'searchable'        => false,
        'filterable'        => false,
        'comparable'        => false,
        'visible_on_front'  => false,
        'visible_in_advanced_search' => false,
        'unique'            => false
    )
);

$installer->addAttribute(
    'order_item', 	// the table it's going to either quote_item or order_item 
    'octopus_deposit_remain', // my new attribute 
	array(
        'type'              => 'decimal',
		'grid'           	=> true,
        'backend'           => '',
        'frontend'          => '',
        //'label'             => 'AutoGenerated '.$_attribute_namespace.' - '.$entity_code,
        'input'             => '',
        'class'             => '',
        'source'            => '',
        'global'            => 2,
        'visible'           => true,
        'required'          => false,
        'user_defined'      => false,
        'default'           => '0',
        'searchable'        => false,
        'filterable'        => false,
        'comparable'        => false,
        'visible_on_front'  => false,
        'visible_in_advanced_search' => false,
        'unique'            => false
    )
);

//Add the custom order status - Deposit Paid
$installer->run("INSERT INTO {$this->getTable('sales_order_status')} (`status`, `label`) VALUES ('octopus_deposit', 'Deposit Paid');");

//Link this status to the STATE - Complete
$installer->run("INSERT INTO {$this->getTable('sales_order_status_state')} (`status`, `state`, `is_default`) VALUES ('octopus_deposit', 'complete', '0');");

$installer->endSetup();